# Generated by Django 2.0.4 on 2018-07-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180727_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
