# Generated by Django 2.0.4 on 2018-07-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180727_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
