# Generated by Django 2.0.4 on 2018-07-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    def estados_tareas(apps, schema_editor):
        Estado = apps.get_model('backend', 'Estado')
        creada = Estado()
        
        creada.id = 1
        creada.nombre = 'Creada'
        creada.save()

        enProceso = Estado()
        enProceso.id = 2
        enProceso.nombre = 'En Proceso'
        enProceso.save()

        terminada = Estado()
        terminada.id = 3
        terminada.nombre = 'Terminada'
        terminada.save()

    dependencies = [
        ('backend', '0005_auto_20180727_1904'),
    ]

    operations = [
        migrations.RunPython(estados_tareas)
    ]
